server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wealthai_db
    username: postgres
    password: "12345"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
      embedding:
        options:
          model: llama3
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: HNSW