spring:
  application:
    name: finsight-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/finsight
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3
        options:
          temperature: 0.7
          num-ctx: 4096
      embedding:
        model: nomic-embed-text

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        initialize-schema: true

server:
  port: 8081
  error:
    include-message: never
    include-stacktrace: never

app:
  jwt:
    secret: ${JWT_SECRET:a_temporary_long_secret_for_dev_only}
    expiration-ms: 86400000   # 24 hours

logging:
  level:
    com.finsight: DEBUG
    org.springframework.ai: INFO
